### ISSUE TITLE
[Feature Request] A new Marker `$xx$` to Paste the Clipboard

### ISSUE THREAD

**Issue by FelipeRearden** [ArianaKhit/text-snippets-obsidian#10]
Hello @ArianaKhit  and @Arax20 !

First of all, thank you very much for this spectacular plug-in. It has a central role in many of my workflows in Obsidian. Thanks for doing this to our community!  

I have a feature that is the creation of an additional `$xx` with a particular behavior. 

I use TextSnippets Obsidian to insert html tags in my notes. Here is my list:
![Screen Shot 2021-06-23 at 11 11 52](https://user-images.githubusercontent.com/85180696/123115565-94750c80-d416-11eb-8a42-5ea10550b532.png)

Lets use `ww : <q>$end$</q>` as an example  

### It works amazing when I have to type a new words

`ww` becomes `<q></q>` and I start to typing the word Obsidian to get `<q>Obsidian</q>`

![Screen Shot 2021-06-23 at 11 24 20](https://user-images.githubusercontent.com/85180696/123115762-b9697f80-d416-11eb-9773-bdf854db63e7.png)

### BUT there is the situation when I am Editing a note

There is a note without any decoration that I wanna apply `<q></q>` in the word `Obsidian` 
To do this, I have to:
- Select the text 
- Cut
- use TextSnippet `ww : <q>$end$</q>`
- Paste to get `<q>Obsidian</q>`

![Screen Shot 2021-06-23 at 11 25 59](https://user-images.githubusercontent.com/85180696/123115901-d736e480-d416-11eb-8000-64fe738df55e.png)
![Screen Shot 2021-06-23 at 11 26 48](https://user-images.githubusercontent.com/85180696/123115944-e158e300-d416-11eb-9a9a-7600869a81bc.png)
![Screen Shot 2021-06-23 at 11 27 11](https://user-images.githubusercontent.com/85180696/123115960-e5850080-d416-11eb-8d2b-8000de4c92a3.png)

### My Request
The creation of a new mark `$xx$` that will PASTE THE CLIPBOARD in the position that `$xx$` is placed. 

This way, I would  create a new snippet:`ee : <q>$xx$</q>` 

`Edit->Cut` the word `Obsidian` and type the new snippet to achieve: `<q>Obsidian</q>`   

I don't know if it is feasible, but would be an amazing feature. A huge time saver!

Let me know if you need more information.  

Have a great day!

**Comment by Arax20** [comment]
I've added this feature to [my fork](https://github.com/Arax20/text-snippets-obsidian).
It may be a while since that's merged though since the last pull request #7 hasn't gone through yet so you might have to manually install the fork for now.

**Comment by FelipeRearden** [comment]
Hello @Arax20 !!! 

Ooowww this is amazing!!!!!

Sorry, I'm a noob at GitHub, I didn't understand what I have to do to get access to this new feature.

I don't know what is fork :(

Can you help me?

Thanks!!!!!!

**Comment by FelipeRearden** [comment]
@Arax20 , I hope you could give some help with the installation. I can wait to use the new `<xx>`  feature. 

I wanna know how to do a manual installation. With files do I have to copy and paste into the `TextSnippet` folder ?

Thanks :)

**Comment by Arax20** [comment]
I've created a release: https://github.com/Arax20/text-snippets-obsidian/releases/tag/0.0.4

If you go ahead and download from the link:
- manifest.json
- data.json
- main.js
- style.css

then put those files in your a new folder in your plugins folder. (something like `\.obsidian\plugins\`)

Make sure you uninstall the previous textsnippet plugin from obsidian first or they might conflict.

**Comment by FelipeRearden** [comment]
Hello @Arax20 !

Thanks for the release! I'm gonna try to do the manual installation  as you said and I ping you when I finish,

Thanks again for doing this feature, it is a great enhancement for my workflow :)

Have a great day!

**Comment by FelipeRearden** [comment]
> I've added this feature to [my fork](https://github.com/Arax20/text-snippets-obsidian):
> 
> ![paste-demo](https://raw.githubusercontent.com/Arax20/text-snippets-obsidian/main/paste_demo.gif)
> 
> It may be a while since that's merged though since the last pull request #7 hasn't gone through yet so you might have to manually install the fork for now.

Hello @ArianaKhit !!!!

Could you please merge this New feature made by @Arax20 in the main release ? This way I can update without losing this feature 🙏 🙏 🙏

This plug-in is very important to me and Is like to get all features :)

Thanks!

Thanks :)

**Comment by ArianaKhit** [comment]
Hello, @FelipeRearden 
I tested this on the new version of plug-in, but, unfortunately, it must be rewritten to work correctly. I am working on it now, so this feature definitely will be in the next release

**Comment by FelipeRearden** [comment]
> Hello, @FelipeRearden 
> 
> I tested this on the new version of plug-in, but, unfortunately, it must be rewritten to work correctly. I am working on it now, so this feature definitely will be in the next release

Thank you very much @ArianaKhit !!!!!!!!! 

I'm grateful to you for making this 😄 😄 😄 😄 😄 😄 😄 😄 !!!!!

**Comment by FelipeRearden** [comment]
Hello @ArianaKhit !!!!

Thanks for the new release `0.0.6` !!!!!

I'm running late today but in about 3 to 4 hours I will update with this new release and I get back with a feedback to you.

Thank you very much !!! We talk later :)

**Comment by FelipeRearden** [comment]
Working perfect on version `0.0.6` in Obsidian `0.12.19` !

Just wanna thanks @Arax20 for all the help before this new release! You are super :)

Have a great day!
