### ISSUE TITLE
[FEATURE] Always trigger snippets

### ISSUE THREAD

**Issue by Cantolla** [ArianaKhit/text-snippets-obsidian#14]
Hello,

Since native text replacements don't work in Obsidian (at least on Mac), would it be possible to set the spacebar as a trigger, essentially always activating the snippets.

Maybe create separate dedicated spaces to always trigger a snippet (spacebar) and an other space to trigger the snippets manually.

Thank you :)

**Comment by ArianaKhit** [comment]
This is really useful feature. I added the option to use the spacebar as a snippet expansion trigger in the settings (disabled by default). Also it will not interrupt normal space behaviour if the cursor is not at the end of the snippet.

**Comment by Cantolla** [comment]
I can't thank you enough, works perfectly!
