### ISSUE TITLE
Can't create right arrow snippet

### ISSUE THREAD

**Issue by rasmusrhl** [ArianaKhit/text-snippets-obsidian#18]
I'm trying to create a right-arrow snippet, using -> as the snippet-text, and trying to get this arrow symbol: →. 

But when  I try to create the snippet in 'Text snippets - settings', by typing or inserting ->, it is changed to the symbol (→). 

Giving me this:
![image](https://user-images.githubusercontent.com/5488079/141186941-3ac8f84d-bb87-4122-834a-f79b636eae1d.png)

Which is not a usable snippet (becuase it does not transform -> into →).

**Comment by Arax20** [comment]
Have you tried actually using that snippet? Obsidian handles settings differently than the editor and one of the differences is that font ligatures are used in the settings pane.

Roughly speaking, some character pairs are combined visually into symbols but this is only visual and doesn't affect the real text content, so even if it looks like a symbol the code should still treat it as `->` and not `→`.

I tried it out and that's how it worked for me at least.

**Comment by rasmusrhl** [comment]
@Arax20 You are absolutely right!
It works just as you said, when I actually try the snippet in the editor.
