### ISSUE TITLE
[BUG] Snippets are not working with Live Preview

### ISSUE THREAD

**Issue by Cantolla** [ArianaKhit/text-snippets-obsidian#21]
Hello,

Pretty much what it says on the title, after the latest Live Preview update the snippets have stopped working, can't trigger them with tab, space or with a hotkey.

Thank you!

**Comment by Cantolla** [comment]
This is true for:
Plugin Version 0.0.6
Running on a Mac Version v0.13.8

**Comment by uwe999** [comment]
if you switch to legacy editor it works

**Comment by olivierdagenais** [comment]
Also reported as #25, with some potential fixes...

**Comment by ArianaKhit** [comment]
Now in LivePreview the hotkey is working, but Tab or Space still cannot trigger replacement.
