### ISSUE TITLE
Issues with expanding ^

### ISSUE THREAD

**Issue by generous-turd** [ArianaKhit/text-snippets-obsidian#22]
I have an expansion for ^ set as:

```
^ : ^{$tb$} $tb$
```

The expansion doesnt seem to work when ^ is enclosed within $ symbols, but works otherwise

For example : writing $a ^$ and hitting tab does nothing

**Comment by ArianaKhit** [comment]
Fixed in 0.1.0
Make sure you added `$` to _Word delimiters_ and removed `{}` symbols from _Word delimiters_ in plugin settings
