### ISSUE TITLE
[BUG] unable to view settings

### ISSUE THREAD

**Issue by cs-mshah** [ArianaKhit/text-snippets-obsidian#36]
On installing and changing the settings from the install, I am not able to find the plugin settings again. Also triggers don't work.
Changed the trigger to some other non conflicting hotkey, disabled tab, enabled live preview.

![image](https://user-images.githubusercontent.com/56499208/156759959-21cd4e53-d42a-43e3-b552-aa45430849a1.png)

![image](https://user-images.githubusercontent.com/56499208/156760023-ad725188-bc09-4f32-aa06-2e0f030dbe6a.png)

As you can see, the settings option is not there to insert new snippets

**Comment by ArianaKhit** [comment]
Have you tried to disable and then enable the plugin?

**Comment by cs-mshah** [comment]
yes, there is no change.

**Comment by renrenxiao** [comment]
you can configure it in json file

**Comment by ArianaKhit** [comment]
Fixed in 0.1.0
