### ISSUE TITLE
Allow expansion also when directly at end of word, not just when ON it

### ISSUE THREAD

**Issue by Moonbase59** [ArianaKhit/text-snippets-obsidian#4]
When typing in an empty line, you can type a shortcut, hit the hotkey and it’ll expand. Fine and natural.

When editing a text, inserting a shortcut and _then_ pressing the hotkey, nothing happens, not even if the shortcut is followed by white space—you _have_ to go back at least one character to be "on" the shortcut word, _then_ hit the hotkey and it works. This feels quite annatural and hinders productivity.

Could it be made so that it expands
- either _on_ the shortcut word (like it does now)
- or _directly adjacent_ to the shortcut word (i.e., at beginning or end, if the shortcut is surrounded by whitespace of any kind)

Example (`|` shall symbolize the cursor, `key` shall be the shortcut):
- `key|` → replace
- `something key| something` → replace
- `something key|board something`→ _don’t_ replace

**Comment by ArianaKhit** [comment]
The problem is fixed, now it works as it should. The shortcut is replaced when the cursor is on the word or at the beginning/end.

**Comment by Moonbase59** [comment]
Fantastic. Thanks a lot for fixing!
