### ISSUE TITLE
[BUG] word delimiters does not work well

### ISSUE THREAD

**Issue by TheAnsIs42** [ArianaKhit/text-snippets-obsidian#41]
I have a snippest looks like:`efr : \frac{$tb$}{$tb$}`and with no "{}" in the `word delimiters` field. But the command does not make the cursor jump to second `$tb$`, the normal snippest like `test : a$tb$b$tb$` works well.
By the way, the setting botton sometimes disappear in the `Third-party plugins` screen.

plugin verison: 0.0.8
obsidian verison: 0.14.2

**Comment by ArianaKhit** [comment]
Fixed in 0.1.0, but without ``{}`` in _Word delimiters_ ``{a}``, where ``a : b`` is the snippet, won`t be replaced by ``{b}``

**Comment by ArianaKhit** [comment]
Now you can both use `efr : \frac{$tb$}{$tb$}` and add `{}` to delimiters (if you want snippets inside `{}` to work).
