### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by osman1963** [ArianaKhit/text-snippets-obsidian#5]
Hi,
First of all, thank you so much for the great plugin.
Second of all, is it possible to add Unicode support. Currently, adding a Unicode (Arabic or Farsi) snippet, either according to the RTL or LTR direction, i.e. snippet : result or result : snippet doesn't work. It acts as if the snippet doesn't exist at all.

Thanks in advance and keep up the great work :)

**Comment by Arax20** [comment]
Can you elaborate on the issue? As far as I am aware unicode is already supported. I'm not familiar with arabic but I tried creating a snippet with arabic I pasted in and it seemed to work:

![arabic_snippet](https://user-images.githubusercontent.com/45805601/141360054-b10c4b66-cf77-424a-b25a-4f367aea30f6.gif)

**Comment by osman1963** [comment]
Thanks for your concern. The issue was fixed in the latest version. My comment is dated May 2021.
