### ISSUE TITLE
a problem with LaTeX

### ISSUE THREAD

**Issue by Ming0330** [ArianaKhit/text-snippets-obsidian#9]
Hello there

Thank you for developing this plugin

During use, a problem was found:

When using LaTex's inline announcement, the input format is'$...$', in this case, you cannot replace the custom phrase

For example, even if abc: \dfrac{$end$}{} is defined, but in the case of $abc$, it cannot be replaced with $\dfrac{}{}$

**Comment by Arax20** [comment]
Are you talking specifically about expanding `$abc$` to trigger the definition for `abc`? Because with my workflow, I type `$abc` which expands normally and then I either add a `$` to the end of the defintion for `abc` or just manually type a `$` to close the environment.

**Comment by y9san9** [comment]
agree with this issue, ran into that problem right now :(

**Comment by y9san9** [comment]
@Arax20 please help here :(
I made a PR fixing my another issue, but I don't know how to fix this one

**Comment by y9san9** [comment]
For me it's useful because I'm doing a lot of math and it's useful for me to have highlighting here

<img width="1440" alt="Снимок экрана 2021-11-04 в 21 13 18" src="https://user-images.githubusercontent.com/46930374/140396194-9b84853a-716d-4b77-a65b-da0613bcf6c9.png">

**Comment by ArianaKhit** [comment]
Fixed in 0.0.5
